title: "Sullivan Lab @ UEA"
description: "Microbial Pathogenesis Research Lab"
url: "https://mattsullivanlab.github.io"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: pages
    values:
      permalink: /
      layout: splash

minimal_mistakes_skin: default

header:
  menu:
    enable: true
    position: right
    color: "#fff"
  social_links:
    enable: false

markdown: kramdown
kramdown:
  input: GFM
