title: "Sullivan Lab @ UEA"
description: "Microbial Pathogenesis Research Lab"
url: ""  # add your GitHub Pages URL later
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

markdown: kramdown
kramdown:
  input: GFM
